# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53bb3a8b6ff971329e2ca0f1bed50ddc77eb7ae24a89cadf57550260741fce2621d4c0c8d579a408c6e84cadbd1f7b6789279ddad8be3dfb6c0dddd8d1baeff3

test:
  secret_key_base: cf5ed3ef0bfad5a1c1445fe09a0eccdca1de551d56e0a55593cd889f505676a33d934723b56595782cbf44f4a01251277e8e2c37e831ee7728a38e4b00ab0515

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
